using CRM.Core.Domain.Users;
using System;
using System.Collections.Generic;
using System.Text;

namespace CRM.Core.Domain
{
    public class Setting : BaseEntity
    {
        /// <summary>
        /// Gets or sets UserId
        /// </summary>
        public int? UserId { get; set; }

        /// <summary>
        /// Gets or sets LanguageId
        /// </summary>
        public int LanguageId { get; set; }

        /// <summary>
        ///virtual User
        /// </summary>
        public virtual User User { get; set; }

        /// <summary>
        /// Gets or sets IsLotNoAutoGenerated
        /// </summary>
        public int? ProjectId { get; set; }
    }
}
